import Head from 'next/head'
import { GetServerSideProps } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/components/Header/Header'
import Banner from '@/components/Banner/Banner'
import ProductFeed from '@/components/ProductFeed/ProductFeed'

const inter = Inter({ subsets: ['latin'] })

type Data = {
  id: number
  title: string
  price: number
  description: string
  category: string
  image: string
  rating: {
    rate: number
    count: number
  }
}

interface Props {
  products: Data[]
}

export default function Home({ products }: Props) {
  return (
    <div className='bg-gray-100'>
      <Head>
        <title>Amazon</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />

      <main className='max-w-6xl mx-auto'>
        <Banner />

        <ProductFeed products={products} />
      </main>
    </div>
  )
}

export const getServerSideProps = async () => {
  const products = await fetch('https://fakestoreapi.com/products')
  const data: Data = await products.json()

  return {
    props: {
      products: data,
    },
  }
}
